name: Deploy to Github Pages # 当前 workflow 的名称
on:
  push:
    branches: # 当 release 分支发生 push 事件，触发该 workflow
      - main

jobs:
  build-and-deploy: # job 的名称
    runs-on: ubuntu-latest # 指定虚拟环境类型

    steps: 
    # 获取当前 repository 代码
    - name: Checkout
      uses: actions/checkout@v3

    # 在工作流中安装 Node v16
    - name: Setup Node.js enviroment
      uses: actions/setup-node@v3
      with:
        node-version: 12

    # 安装依赖，执行 yarn build
    - name: Install dependencies && Build application
      env:
        BASE: 'blog' # 配置环境变量
      run: yarn install && yarn build

    # 将打包后的产物部署到 Github Pages 上
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./build
      
